---
preset: "extended"
changelog:
  path: "CHANGELOG.md"
  sections:
    "Added": "^(feat|chore\\(deps\\)|fix\\(deps\\))$"
    "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://example.com/issues/%s)"
commitMessageConventions: 
  enabled: 
    - conventionalCommits
  items: 
    conventionalCommits: 
      expression: "(?m)^(?<type>[a-zA-Z0-9_]+)(!)?(\\((?<scope>[a-z ]+)\\))?:( (?<title>.+))$(?s).*"
      bumpExpressions: 
        major: "(?s)(?m)^[a-zA-Z0-9_]+(!|.*^(BREAKING( |-)CHANGE: )).*"
        minor: "(?s)(?m)^feat(?!!|.*^(BREAKING( |-)CHANGE: )).*"
        patch: "(?s)(?m)^fix(?!!|.*^(BREAKING( |-)CHANGE: )).*"
initialVersion: "0.1.0"
releasePrefix: v
releaseTypes:
  publicationServices: 
    - github
scheme: SEMVER
git:
  remotes:
    origin:
      authenticationMethod: USER_PASSWORD
      user: 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
      password: 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
services: 
  github: 
    type: "GITHUB"
    options: 
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "proguard-core-visualizer"
      REPOSITORY_OWNER: "Mouwrice"
