name: Conveyor Deploy
on:  [workflow_dispatch]

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle jvmJar
      run: ./gradlew jvmJar

    - name: Run Conveyor     
      uses: hydraulic-software/conveyor/actions/build@v10.1
      env:
        OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        command: make copied-site
        signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}          
        agree_to_license: 1
